# Generated by Django 4.0.3 on 2022-04-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookName', models.CharField(max_length=200)),
                ('AuthorOfBook', models.CharField(max_length=200)),
                ('PublishedYear', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Books_Table',
            },
        ),
    ]
