# Generated by Django 4.0.1 on 2022-04-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0002_bookstable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintable',
            name='Firstname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='admintable',
            name='Lastname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='admintable',
            name='Password',
            field=models.CharField(max_length=50),
        ),
    ]
